/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SVRF.Client.Client.SwaggerDateConverter;

namespace SVRF.Client.Model
{
    /// <summary>
    /// The type of the Media. This should influence the media controls displayed to the user.
    /// </summary>
    /// <value>The type of the Media. This should influence the media controls displayed to the user.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum MediaType
    {
        
        /// <summary>
        /// Enum Photo for value: photo
        /// </summary>
        [EnumMember(Value = "photo")]
        Photo = 1,
        
        /// <summary>
        /// Enum Video for value: video
        /// </summary>
        [EnumMember(Value = "video")]
        Video = 2,
        
        /// <summary>
        /// Enum _3d for value: 3d
        /// </summary>
        [EnumMember(Value = "3d")]
        _3d = 3
    }

}
