/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing MediaMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaMetadataTests
    {
        // TODO uncomment below to declare an instance variable for MediaMetadata
        //private MediaMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaMetadata
            //instance = new MediaMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaMetadata
        /// </summary>
        [Test]
        public void MediaMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaMetadata
            //Assert.IsInstanceOfType<MediaMetadata> (instance, "variable 'instance' is a MediaMetadata");
        }


        /// <summary>
        /// Test the property 'HasBlendShapes'
        /// </summary>
        [Test]
        public void HasBlendShapesTest()
        {
            // TODO unit test for the property 'HasBlendShapes'
        }
        /// <summary>
        /// Test the property 'IsFaceFilter'
        /// </summary>
        [Test]
        public void IsFaceFilterTest()
        {
            // TODO unit test for the property 'IsFaceFilter'
        }
        /// <summary>
        /// Test the property 'RequiresBlendShapes'
        /// </summary>
        [Test]
        public void RequiresBlendShapesTest()
        {
            // TODO unit test for the property 'RequiresBlendShapes'
        }

    }

}
