/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing MediaVideos
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaVideosTests
    {
        // TODO uncomment below to declare an instance variable for MediaVideos
        //private MediaVideos instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaVideos
            //instance = new MediaVideos();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaVideos
        /// </summary>
        [Test]
        public void MediaVideosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaVideos
            //Assert.IsInstanceOfType<MediaVideos> (instance, "variable 'instance' is a MediaVideos");
        }


        /// <summary>
        /// Test the property '_848'
        /// </summary>
        [Test]
        public void _848Test()
        {
            // TODO unit test for the property '_848'
        }
        /// <summary>
        /// Test the property '_1440'
        /// </summary>
        [Test]
        public void _1440Test()
        {
            // TODO unit test for the property '_1440'
        }
        /// <summary>
        /// Test the property '_2160'
        /// </summary>
        [Test]
        public void _2160Test()
        {
            // TODO unit test for the property '_2160'
        }
        /// <summary>
        /// Test the property '_4096'
        /// </summary>
        [Test]
        public void _4096Test()
        {
            // TODO unit test for the property '_4096'
        }
        /// <summary>
        /// Test the property 'Clip'
        /// </summary>
        [Test]
        public void ClipTest()
        {
            // TODO unit test for the property 'Clip'
        }
        /// <summary>
        /// Test the property 'Hls'
        /// </summary>
        [Test]
        public void HlsTest()
        {
            // TODO unit test for the property 'Hls'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }

    }

}
