/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing MediaFiles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaFilesTests
    {
        // TODO uncomment below to declare an instance variable for MediaFiles
        //private MediaFiles instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaFiles
            //instance = new MediaFiles();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaFiles
        /// </summary>
        [Test]
        public void MediaFilesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaFiles
            //Assert.IsInstanceOfType<MediaFiles> (instance, "variable 'instance' is a MediaFiles");
        }


        /// <summary>
        /// Test the property 'Glb'
        /// </summary>
        [Test]
        public void GlbTest()
        {
            // TODO unit test for the property 'Glb'
        }
        /// <summary>
        /// Test the property 'GlbDraco'
        /// </summary>
        [Test]
        public void GlbDracoTest()
        {
            // TODO unit test for the property 'GlbDraco'
        }
        /// <summary>
        /// Test the property 'Gltf'
        /// </summary>
        [Test]
        public void GltfTest()
        {
            // TODO unit test for the property 'Gltf'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Stereo'
        /// </summary>
        [Test]
        public void StereoTest()
        {
            // TODO unit test for the property 'Stereo'
        }
        /// <summary>
        /// Test the property 'Videos'
        /// </summary>
        [Test]
        public void VideosTest()
        {
            // TODO unit test for the property 'Videos'
        }

    }

}
