/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing MediaImages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaImagesTests
    {
        // TODO uncomment below to declare an instance variable for MediaImages
        //private MediaImages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaImages
            //instance = new MediaImages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaImages
        /// </summary>
        [Test]
        public void MediaImagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaImages
            //Assert.IsInstanceOfType<MediaImages> (instance, "variable 'instance' is a MediaImages");
        }


        /// <summary>
        /// Test the property '_136'
        /// </summary>
        [Test]
        public void _136Test()
        {
            // TODO unit test for the property '_136'
        }
        /// <summary>
        /// Test the property '_540'
        /// </summary>
        [Test]
        public void _540Test()
        {
            // TODO unit test for the property '_540'
        }
        /// <summary>
        /// Test the property '_720'
        /// </summary>
        [Test]
        public void _720Test()
        {
            // TODO unit test for the property '_720'
        }
        /// <summary>
        /// Test the property '_1080'
        /// </summary>
        [Test]
        public void _1080Test()
        {
            // TODO unit test for the property '_1080'
        }
        /// <summary>
        /// Test the property '_4096'
        /// </summary>
        [Test]
        public void _4096Test()
        {
            // TODO unit test for the property '_4096'
        }
        /// <summary>
        /// Test the property '_8192'
        /// </summary>
        [Test]
        public void _8192Test()
        {
            // TODO unit test for the property '_8192'
        }
        /// <summary>
        /// Test the property '_1080Watermarked'
        /// </summary>
        [Test]
        public void _1080WatermarkedTest()
        {
            // TODO unit test for the property '_1080Watermarked'
        }
        /// <summary>
        /// Test the property '_720x405'
        /// </summary>
        [Test]
        public void _720x405Test()
        {
            // TODO unit test for the property '_720x405'
        }
        /// <summary>
        /// Test the property '_720x540'
        /// </summary>
        [Test]
        public void _720x540Test()
        {
            // TODO unit test for the property '_720x540'
        }
        /// <summary>
        /// Test the property '_720x720'
        /// </summary>
        [Test]
        public void _720x720Test()
        {
            // TODO unit test for the property '_720x720'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }

    }

}
