/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing PaginationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaginationResponseTests
    {
        // TODO uncomment below to declare an instance variable for PaginationResponse
        //private PaginationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaginationResponse
            //instance = new PaginationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaginationResponse
        /// </summary>
        [Test]
        public void PaginationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaginationResponse
            //Assert.IsInstanceOfType<PaginationResponse> (instance, "variable 'instance' is a PaginationResponse");
        }


        /// <summary>
        /// Test the property 'NextPageNum'
        /// </summary>
        [Test]
        public void NextPageNumTest()
        {
            // TODO unit test for the property 'NextPageNum'
        }
        /// <summary>
        /// Test the property 'PageNum'
        /// </summary>
        [Test]
        public void PageNumTest()
        {
            // TODO unit test for the property 'PageNum'
        }

    }

}
