/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing SearchMediaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchMediaResponseTests
    {
        // TODO uncomment below to declare an instance variable for SearchMediaResponse
        //private SearchMediaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchMediaResponse
            //instance = new SearchMediaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchMediaResponse
        /// </summary>
        [Test]
        public void SearchMediaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchMediaResponse
            //Assert.IsInstanceOfType<SearchMediaResponse> (instance, "variable 'instance' is a SearchMediaResponse");
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'NextPageNum'
        /// </summary>
        [Test]
        public void NextPageNumTest()
        {
            // TODO unit test for the property 'NextPageNum'
        }
        /// <summary>
        /// Test the property 'PageNum'
        /// </summary>
        [Test]
        public void PageNumTest()
        {
            // TODO unit test for the property 'PageNum'
        }
        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Test]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }
        /// <summary>
        /// Test the property 'TookMs'
        /// </summary>
        [Test]
        public void TookMsTest()
        {
            // TODO unit test for the property 'TookMs'
        }
        /// <summary>
        /// Test the property 'TotalNum'
        /// </summary>
        [Test]
        public void TotalNumTest()
        {
            // TODO unit test for the property 'TotalNum'
        }

    }

}
