/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SVRF.Client.Api;
using SVRF.Client.Model;
using SVRF.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SVRF.Client.Test
{
    /// <summary>
    ///  Class for testing StereoscopicType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StereoscopicTypeTests
    {
        // TODO uncomment below to declare an instance variable for StereoscopicType
        //private StereoscopicType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StereoscopicType
            //instance = new StereoscopicType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StereoscopicType
        /// </summary>
        [Test]
        public void StereoscopicTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StereoscopicType
            //Assert.IsInstanceOfType<StereoscopicType> (instance, "variable 'instance' is a StereoscopicType");
        }



    }

}
